# Generated by Django 5.2.7 on 2025-10-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='idade',
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_de_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
