# Generated by Django 5.2.7 on 2025-10-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='escolher_foco',
            new_name='Fisico',
        ),
    ]
