# Generated by Django 6.0 on 2025-12-09 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_descricao'),
        ('produtos', '0003_remove_produto_cor_remove_produto_tamanho_and_more'),
    ]

    operations = [
    ]
