# Generated by Django 6.0 on 2025-12-09 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_merge_20251209_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
    ]
